name: cicd pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        run: |
          docker build -t 653492891194.dkr.ecr.ap-northeast-1.amazonaws.com/coursera_tuts/ci_pipeline:latest .
          docker push 653492891194.dkr.ecr.ap-northeast-1.amazonaws.com/coursera_tuts/ci_pipeline:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_IP_ADDRESS }}
          username: ubuntu
          key: ${{ secrets.EC2_ACCESS_KEY }}
          script: |
            docker pull 653492891194.dkr.ecr.ap-northeast-1.amazonaws.com/coursera_tuts/ci_pipeline:latest
            docker compose up -d
