name: CD/CI pipeline


on:
  push:
    branches:
      - main  
  workflow dispatch:
jobs:
  build: 
    runs-on: ubuntu-linux
    steps:
      -name: Check the code
        uses: actions/checkout@latest
      -name: Build Docker image
        uses: Docker Build -t spring-boot-app:latest